#include<iostream>
#include<iomanip>
using namespace std;
int main()
{
	cout<<setw(10)<<"*"<<endl<<
	setw(11)<<"***"<<endl<<
	setw(12)<<"*****"<<endl<<
	setw(13)<<"*******"<<endl<<
	setw(14)<<"*********"<<endl<<
	setw(11)<<"***"<<endl<<
	setw(12)<<"*****"<<endl<<
	setw(13)<<"*******"<<endl<<
	setw(14)<<"*********"<<endl<<
	setw(15)<<"***********"<<endl<<
	setw(16)<<"*************"<<endl<<
	setw(12)<<"*****"<<endl<<
	setw(13)<<"*******"<<endl<<
	setw(14)<<"*********"<<endl<<
	setw(15)<<"***********"<<endl<<
	setw(16)<<"*************"<<endl<<
	setw(17)<<"***************"<<endl<<
	setw(18)<<"*****************"<<endl<<
	setw(12)<<"*****"<<endl<<
	setw(12)<<"*****"<<endl<<
	setw(12)<<"*****"<<endl<<
	setw(12)<<"*****"<<endl<<
	setw(12)<<"*****"<<endl<<
	setw(12)<<"*****"<<endl<<
	setw(12)<<"*****"<<endl<<
	setw(12)<<"*****"<<endl<<
	setw(12)<<"*****"<<endl;
}
